cashscore/accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views


app_name = 'accounts'

urlpatterns = [
    path('activate/<uidb64>/<token>/', views.ActivationView.as_view(), name='activate'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('account/', views.AccountView.as_view(), name='account'),
    path('account/payment-methods/', views.PaymentMethodsView.as_view(), name='payment_methods'),
    path('account/payment-methods/delete/<id>/', views.DeletePaymentMethodView.as_view(), name='delete_payment_method'),
    path('account/payment-methods/set-default/<id>/', views.SetDefaultPaymentMethodView.as_view(), name='set_default_payment_method'),
    path('password-reset/', views.PasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

cashscore/config/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('', include('cashscore.accounts.urls', namespace='accounts')),
    path('', include('cashscore.score.urls', namespace='score')),
    path('', include('cashscore.web.urls', namespace='web')),
    path('admin/', admin.site.urls),
    path('stripe/', include("djstripe.urls", namespace="djstripe")),
]

cashscore/score/urls.py
from django.urls import path

from . import views


app_name = 'score'

urlpatterns = [
    path('applications/', views.ApplicationsView.as_view(), name='applications'),
    path('add-applicant/', views.AddApplicantView.as_view(), name='add_applicant'),
    path('add-property/', views.AddPropertyView.as_view(), name='add_property'),
    path('report/<int:pk>/', views.ReportDetailView.as_view(), name='report'),
    path('applicant/<aidb64>/<token>/', views.ApplicantView.as_view(), name='applicant_entry'),
]

cashscore/web/urls.py
from django.urls import path

from . import views


app_name = 'web'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
]

cashscore/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms

from djstripe import settings as djstripe_settings

from .models import User
from .widgets import StripeElementWidget


class AddPaymentMethodForm(forms.Form):
    stripe_token = forms.CharField(
        widget=StripeElementWidget(djstripe_settings.STRIPE_PUBLIC_KEY),
        label='Debit or credit card',)
    is_default = forms.BooleanField(label='Set as default', required=False)

    def __init__(self, customer, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.customer = customer

    def clean_is_default(self):
        is_default = self.cleaned_data.get('is_default')
        if self.customer.legacy_cards.count() == 0 and not is_default:
            raise forms.ValidationError('This field is required.')

        return is_default

    def save(self):
        return self.customer.add_card(
            self.cleaned_data['stripe_token'],
            set_default=self.cleaned_data['is_default'])


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name',)

cashscore/score/forms.py
from django import forms
from django.core import validators

from .models import Application, Property


class ApplicationForm(forms.ModelForm):
    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['user_property'].queryset = Property.objects.filter(user=user)
        self.fields['applicant_name'].widget.attrs.update({ 'autofocus': True })

    class Meta:
        model = Application
        fields = ( 'applicant_name', 'applicant_email', 'user_property', 'unit', 'rent_asked',)


class CommaSeperatedField(forms.Field):
    def __init__(self, min_length=None, max_length=None, **kwargs):
        self.min_length = min_length
        self.max_length = max_length
        super().__init__(**kwargs)
        if min_length is not None:
            self.validators.append(validators.MinLengthValidator(int(min_length)))
        if max_length is not None:
            self.validators.append(validators.MaxLengthValidator(int(max_length)))

    def to_python(self, value):
        value = str(value)
        return value.split(',')


class ApplicantForm(forms.Form):
    tokens = CommaSeperatedField(min_length=1, widget=forms.HiddenInput())


class PropertyForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['address'].widget.attrs.update({ 'autofocus': True })

    class Meta:
        model = Property
        fields = ('address',)

cashscore/accounts/views.py
from django.contrib import messages
from django.contrib.auth import views as auth_views
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.sites.shortcuts import get_current_site
from django.core.exceptions import ValidationError
from django.core.mail import EmailMessage
from django.http import HttpResponseRedirect, Http404
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views import View
from django.views.generic import DeleteView, FormView

from djstripe.models import Card, DjstripePaymentMethod
from stripe.error import CardError, InvalidRequestError

from .forms import AddPaymentMethodForm, SignUpForm
from .models import User
from .tokens import account_activation_token


class SignUpView(FormView):
    template_name = 'accounts/signup.html'
    form_class = SignUpForm
    success_url = reverse_lazy('web:home')

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = False
        user.save()

        mail_subject = 'Activate your CashScore account'
        message = render_to_string('accounts/activate-account-email.html', {
            'user': user,
            'domain': get_current_site(self.request).domain,
            'protocol': 'https' if self.request.is_secure() else 'http',
            'uid': urlsafe_base64_encode(force_bytes(user.id)),
            'token': account_activation_token.make_token(user),
        })
        to_email = form.cleaned_data.get('email')
        email = EmailMessage(
            mail_subject,
            message,
            to=[to_email])
        email.send()

        messages.success(self.request, 'Please confirm your email address to complete the registration.')

        return super().form_valid(form)


class ActivationView(View):
    def get(self, request, uidb64, token):
        try:
            uid = urlsafe_base64_decode(uidb64).decode()
            user = User.objects.get(id=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist, ValidationError):
            user = None

        if user is not None and account_activation_token.check_token(user, token):
            user.is_active = True
            user.save()

            messages.success(request, 'Your email has been confirmed. You can now login.')

            return HttpResponseRedirect(reverse_lazy('accounts:login'))
        else:
            messages.error(request, 'Activation link is invalid.')
            return HttpResponseRedirect(reverse_lazy('web:home'))


class PasswordResetView(auth_views.PasswordResetView):
    email_template_name = 'accounts/password-reset-email.html'
    template_name = 'accounts/password-reset.html'
    success_url = reverse_lazy('accounts:password_reset_done')


class PasswordResetDoneView(auth_views.PasswordResetDoneView):
    template_name = 'accounts/password-reset-done.html'


class PasswordResetConfirmView(auth_views.PasswordResetConfirmView):
    template_name = 'accounts/password-reset-confirm.html'
    success_url = reverse_lazy('accounts:password_reset_complete')


class PasswordResetCompleteView(auth_views.PasswordResetCompleteView):
    template_name = 'accounts/password-reset-complete.html'


class AccountView(LoginRequiredMixin, FormView):
    template_name = 'accounts/account.html'
    form_class = PasswordChangeForm
    success_url = reverse_lazy('accounts:login')

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs


class PaymentMethodsView(LoginRequiredMixin, FormView):
    template_name = 'accounts/payment-methods.html'
    form_class = AddPaymentMethodForm
    success_url = reverse_lazy('accounts:payment_methods')

    def form_valid(self, form):
        try:
            form.save()
            messages.success(self.request, 'Succesfully added a new payment method.')
            return super().form_valid(form)
        except (CardError, InvalidRequestError) as e:
            messages.error(self.request, 'Error adding new card.')

        return super().form_invalid(form)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['customer'] = self.request.user.stripe_customer
        return kwargs


class DeletePaymentMethodView(LoginRequiredMixin, View):
    def post(self, request, id):
        try:
            customer = request.user.stripe_customer
            card = customer.legacy_cards.get(id=id)
            card.remove()

            messages.success(request, 'Successfully deleted a payment method.')
        except Card.DoesNotExist:
            raise Http404()

        return HttpResponseRedirect(reverse_lazy('accounts:payment_methods'))


class SetDefaultPaymentMethodView(LoginRequiredMixin, View):
    def post(self, request, id):
        try:
            customer = request.user.stripe_customer
            card = customer.legacy_cards.get(id=id)

            if customer.default_source.resolve() == card:
                return HttpResponseRedirect(reverse_lazy('accounts:payment_methods'))

            stripe_customer = customer.api_retrieve()
            stripe_customer.default_source = card.id
            stripe_customer.save()

            customer.default_source = DjstripePaymentMethod.objects.get(id=card.id)
            customer.save()

            messages.success(request, 'Successfully updated your default payment method.')
        except Card.DoesNotExist:
            raise Http404()

        return HttpResponseRedirect(reverse_lazy('accounts:payment_methods'))

cashscore/score/views.py
import uuid

from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.sites.shortcuts import get_current_site
from django.db import transaction
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.utils.http import urlsafe_base64_decode
from django.views.generic import FormView, TemplateView

from celery import chain

from .forms import ApplicationForm, ApplicantForm, PropertyForm
from .models import Application, Item, Property
from .tasks import send_email_to_applicant, get_applicant_transactions, charge_client_for_application, send_email_to_client
from .tokens import application_token


class ApplicationsView(LoginRequiredMixin, TemplateView):
    template_name = 'score/applications.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['properties'] = self.request.user.properties.all()
        return context


class AddApplicantView(LoginRequiredMixin, FormView):
    template_name = 'score/add-applicant.html'
    form_class = ApplicationForm
    success_url = reverse_lazy('score:applications')

    def form_valid(self, form):
        application = form.save()

        protocol = 'https' if self.request.is_secure() else 'http'
        domain = get_current_site(self.request).domain
        token = application_token.make_token(application)
        send_email_to_applicant.delay(
            application.id,
            protocol,
            domain,
            token)

        return super().form_valid(form)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs


INTERNAL_APPLICANT_ENTRY_SESSION_TOKEN = '_applicant_entry_token'


class ApplicantView(FormView):
    url_token = 'start-application'
    template_name = 'score/applicant.html'
    form_class = ApplicantForm
    success_url = reverse_lazy('web:home')

    def dispatch(self, *args, **kwargs):
        try:
            application_id = urlsafe_base64_decode(kwargs['aidb64']).decode()
            self.application = Application.objects.get(id=application_id)
        except (TypeError, ValueError, OverflowError, Application.DoesNotExist, Application):
            self.application = None

        if self.application is not None:
            token = kwargs['token']
            if token == self.url_token:
                session_token = self.request.session.get(
                    INTERNAL_APPLICANT_ENTRY_SESSION_TOKEN)
                if application_token.check_token(self.application, session_token):
                    return super().dispatch(*args, **kwargs)
            else:
                if application_token.check_token(self.application, token):
                    # It's important to redirect here to avoid the token being
                    # leaked in the HTTP Referer header.
                    self.request.session[INTERNAL_APPLICANT_ENTRY_SESSION_TOKEN] = token
                    redirect_url = self.request.path.replace(token, self.url_token)
                    return HttpResponseRedirect(redirect_url)

        return HttpResponseRedirect(reverse_lazy('web:home'))

    def form_valid(self, form):
        self.application.applicant_connected_to_plaid = True
        self.application.save()

        chain(
            # Get Applicant Transactions
            get_applicant_transactions.si(
                self.application.id,
                form.cleaned_data.get('tokens'),),
            # Charge only once all transactions have been pulled
            charge_client_for_application.si(
                self.application.id,
                uuid.uuid4()),
            # Notify client only once the charge has been made
            send_email_to_client.si(
                self.application.id,
                'https' if self.request.is_secure() else 'http',
                get_current_site(self.request).domain),
        )()

        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['application'] = self.application
        context['PLAID_ENV'] = settings.PLAID_ENV
        context['PLAID_PUBLIC_KEY'] = settings.PLAID_PUBLIC_KEY
        return context


class AddPropertyView(LoginRequiredMixin, FormView):
    template_name = 'score/add-property.html'
    form_class = PropertyForm
    success_url = reverse_lazy('score:applications')

    def form_valid(self, form):
        property = form.save(commit=False)
        property.user = self.request.user
        property.save()

        return super().form_valid(form)

cashscore/web/views.py
from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = 'web/home.html'

cashscore/templates/score/add-applicant.html
{% extends 'base.html' %}

{% block content %}
    <div class="container pt-3">
        <h4>Add Applicant</h4>
        <form method="post" novalidate>
            {% csrf_token %}
            {% include 'includes/form.html' %}
            <button class="button-primary">Add Applicant</button>
        </form>
    </div>
{% endblock %}

cashscore/templates/score/add-property.html
{% extends 'base.html' %}

{% block content %}
    <div class="container pt-3">
        <h4>Add Property</h4>
        <form method="post" novalidate>
            {% csrf_token %}
            {% include 'includes/form.html' %}
            <button class="button-primary">Add Property</button>
        </form>
    </div>
{% endblock %}

cashscore/templates/score/applicant-request-email.html
{% extends 'base.html' %}

{% block body %}
    <p>
        Hi {{ application.applicant_name }},
        Click the button below to complete the application
    </p>
    <a class="button button-primary" href="{{ protocol }}://{{ domain }}{% url 'score:applicant_entry' aidb64=aidb64 token=token %}">
        Complete Application
    </a>
{% endblock %}

cashscore/templates/score/applicant-request.html
{% extends 'base.html' %}

{% block body %}
    <p>
        Hi {{ application.applicant_name }},
        Click the button below to complete the application
    </p>
    <a class="button button-primary" href="{{ protocol }}://{{ domain }}{% url 'score:applicant_entry' aidb64=aidb64 token=token %}">
        Complete Application
    </a>
{% endblock %}

cashscore/templates/score/applicant.html
{% extends 'base.html' %}

{% block content %}
    <div class="container pt-3">
        <h2 class="text-align-center">
            Welcome {{ application.applicant_name }}
        </h2>
        <form id="link-form" method="post" novalidate>
            {% csrf_token %}
            <div class="text-align-center">
                <button class="button button-primary" type="submit" disabled>
                    Finish Application
                </button>
                <span class="mx-2">or</span>
                <button class="button button-primary" id="add-accounts-button" type="button">
                    Link Accounts
                </button>
            </div>
        </form>
        <hr/>
        <h4>
            Linked Accounts
        </h4>
        <div class="list mb-1 full-width" id="accounts-list">
            You have not linked any accounts yet.
        </div>
    </div>
{% endblock %}

{% block javascript %}
    <script src="https://cdn.plaid.com/link/v2/stable/link-initialize.js"></script>
    <script type="text/javascript">
        (function($) {
            var tokens = [];
            var $form = $('#link-form');
            var $formSubmitButton = $form.find('button[type="submit"]');
            var $addAccountsButton = $('#add-accounts-button');
            var $accountsList = $('#accounts-list');
            var handler = Plaid.create({
                clientName: 'CashScore',
                env: '{{ PLAID_ENV }}',
                key: '{{ PLAID_PUBLIC_KEY }}',
                product: ['transactions'],
                onSuccess: function(public_token, metadata) {
                    if (tokens.length === 0) {
                        $accountsList.empty();
                        $formSubmitButton.prop('disabled', false);
                    }
                    tokens.push(public_token);
                    for (var account of metadata.accounts) {
                        $accountsList.append($('<div/>', {
                            class: 'list-item',
                            text: metadata.institution.name + ' - ' + account.name,
                        }).append($('<small/>', {
                            class: 'ml-1',
                            text: account.mask
                        })));
                    }
                },
            });

            $form.on('submit', function(e) {
                if (tokens.length === 0) {
                    e.preventDefault();
                    return;
                }
                $('<input/>', {
                    type: 'hidden',
                    name: 'tokens',
                    value: tokens.join(','),
                }).appendTo($form);
            });

            $addAccountsButton.on('click', function(e) {
                handler.open();
            })
        })(jQuery);
    </script>
{% endblock %}

cashscore/templates/score/applications.html
{% extends 'base.html' %}
{% load fontawesome_5 %}

{% block content %}
    <div class="container pt-3">
        <div class="flex align-items-center justify-content-between">
            <h4 class="mb-0">My Applications</h4>
            <div>
                <a class="button button-primary mb-0 mr-1" href="{% url 'score:add_applicant' %}">Add Applicant</a>
                <a class="button mb-0" href="{% url 'score:add_property' %}">Add Property</a>
            </div>
        </div>
        <table class="full-width mt-3">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Property</th>
                    <th>Email</th>
                    <th>Completed</th>
                    <th>View Report</th>
                </tr>
            </thead>
            <tbody>
                {% for property in properties %}
                    {% for application in property.applications.all %}
                        <tr>
                            <td>{{ application.applicant_name }}</td>
                            <td>{{ property.address }}</td>
                            <td>{{ application.applicant_email }}</td>
                            <td class="text-align-center">
                                {% if application.is_completed %}
                                {% fa5_icon 'check-circle' 'fas' class='fa-lg primary' %}
                                {% else %}
                                {% fa5_icon 'times-circle' 'fas' class='fa-lg danger' %}
                                {% endif %}
                            </td>
                            <th><a class="button mb-0{% if not application.is_completed %} disabled{% endif %}" href="#">View Report</a>
                        </tr>
                    {% endfor %}
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

cashscore/templates/score/client-report-available-email.html
{% extends 'base.html' %}

{% block body %}
    <p>
        Hi {{ client.get_full_name }},
        Click the button below to view the report for {{ application.applicant_name }}
    </p>
    <a class="button button-primary" href="#">
        View Report
    </a>
{% endblock %}

cashscore/templates/score/reports.html
{% extends 'base.html' %}

{% block content %}
    <div class="container pt-3">
        <h4 class="mb-0">Cash Flows</h4>
        <h4 class="mb-0">Expenses</h4>
        <h4 class="mb-0">Income</h4>
        <h4 class="mb-0">Funds</h4>
        <table class="full-width mt-3">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Amount</th>
                    <th>Memo</th>
                </tr>
            </thead>
            <tbody>
                {% for transaction in transactions %}
                    <tr>
                        <td>{{ transaction.date }}</td>
                        <td>{{ transaction.amount }}</td>
                        <td>{{ transaction.name }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}